### ISSUE TITLE
local development error: Clone/fork the repository as a local library and npm link it, but app failed 

### ISSUE THREAD

**Issue by johnking** [VadimDez/ng2-pdf-viewer#257]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
1. I forked and cloned the repository to local
2. build and npm/yarn link the library
3. compile the host app with following warnings

```
WARNING in ./node_modules/ng2-pdf-viewer/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/johnking/repos/beStudy/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/johnking/repos/beStudy/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/Users/johnking/repos/beStudy/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/Users/johnking/repos/beStudy/node_modules/webpack/lib/Compiler.js:502:17)
    at /Users/johnking/repos/beStudy/node_modules/tapable/lib/Tapable.js:289:11

    at _addModuleChain (/Users/johnking/repos/beStudy/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/Users/johnking/repos/beStudy/node_modules/webpack/lib/Compilation.js:477:14)
    at process._tickCallback (internal/process/next_tick.js:150:11)
 @ ./node_modules/ng2-pdf-viewer/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng2-pdf-viewer/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```
4. running the app with following errors

```

(anonymous) @ scripts.bundle.js:sourcemap:25700
pdf.js:7064 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
supportsMozChunkedClosure @ pdf.js:7064
Object.defineProperty.value @ pdf.js:7069
__w_pdfjs_require__ @ pdf.js:45
_typeof @ pdf.js:14820
__w_pdfjs_require__ @ pdf.js:45
Object.defineProperty.value @ pdf.js:91
(anonymous) @ pdf.js:94
webpackUniversalModuleDefinition @ pdf.js:18
(anonymous) @ pdf.js:25
(anonymous) @ pdf.js:16404
../../../../ng2-pdf-viewer/node_modules/pdfjs-dist/build/pdf.js @ vendor.bundle.js:2384
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ pdf-viewer.component.js:8
../../../../ng2-pdf-viewer/dist/pdf-viewer.component.js @ vendor.bundle.js:2369
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ index.js:4
../../../../ng2-pdf-viewer/dist/index.js @ vendor.bundle.js:2361
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ app.module.ts:49
../../../../../src/app/app.module.ts @ main.bundle.js:95
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ main.ts:4
../../../../../src/main.ts @ main.bundle.js:891
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:913
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
compiler.js:485 Uncaught Error: Unexpected value 'PdfViewerModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:485)
    at eval (compiler.js:15226)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15201)
    at JitCompiler._loadModules (compiler.js:34398)
    at JitCompiler._compileModuleAndComponents (compiler.js:34359)
    at JitCompiler.compileModuleAsync (compiler.js:34253)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:239)
    at PlatformRef.bootstrapModule (core.js:5561)
    at eval (main.ts:11)
syntaxError @ compiler.js:485
(anonymous) @ compiler.js:15226
CompileMetadataResolver.getNgModuleMetadata @ compiler.js:15201
JitCompiler._loadModules @ compiler.js:34398
JitCompiler._compileModuleAndComponents @ compiler.js:34359
JitCompiler.compileModuleAsync @ compiler.js:34253
CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:239
PlatformRef.bootstrapModule @ core.js:5561
(anonymous) @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:891
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:913
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
client:147 [WDS] Warnings while compiling.
warnings @ client:147
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
client:153 ./node_modules/ng2-pdf-viewer/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ng2-pdf-viewer/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng2-pdf-viewer/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
warnings @ client:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543
client:153 ./node_modules/ng2-pdf-viewer/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ng2-pdf-viewer/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng2-pdf-viewer/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
warnings @ client:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:421
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543

```

I am using: 
```
Angular CLI: 1.6.5
Node: 9.4.0
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0

@angular/cli: 1.6.5
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0

```

May the author or contributors help me to resolve the issue? 

thanks a lot

-John

**Comment by johnking** [comment]
I am closing this issue, because I have to use [Generator-angular-2-library](https://github.com/jvandemo/generator-angular2-library) as a library seed.
