### ISSUE TITLE
Not working on prod build 

### ISSUE THREAD

**Issue by paresh2190** [VadimDez/ng2-pdf-viewer#258]
build prod failed: Cannot read property 'PdfViewerComponent' of undefined, resolving symbol PdfViewerModule
            in F:/apps/Foundations/node_modules/ng2-pdf-viewer/dist/index.d.ts, resolving symbol PdfViewerModule in
            F:/apps/Foundations/node_modules/ng2-pdf-viewer/dist/index.d.ts
Error: Cannot read property 'PdfViewerComponent' of undefined, resolving symbol PdfViewerModule in F:/apps/Foundations/node_modules/ng2-pdf-viewer/dist/index.d.ts, resolving symbol PdfViewerModule in F:/apps/Foundations/node_modules/ng2-pdf-viewer/dist/index.d.ts
    at simplifyInContext (F:\apps\Foundations\node_modules\@angular\compiler-cli\src\static_reflector.js:475:23)
    at StaticReflector.simplify (F:\apps\Foundations\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (F:\apps\Foundations\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at NgModuleResolver.resolve (F:\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (F:\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (F:\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (F:\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at F:\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (F:\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)

**Comment by VadimDez** [comment]
Are you using `ng-cli`?

**Comment by paresh2190** [comment]
Yes.
Thanks for your valuable reply. I have sorted by updating the angular cli dependencies from 2 to 4

**Comment by VadimDez** [comment]
Please close the issue if it's working for you

**Comment by paresh2190** [comment]
ok
