### ISSUE TITLE
Cannot read property 'sendWithPromise' of null error

### ISSUE THREAD

**Issue by fncamm** [VadimDez/ng2-pdf-viewer#382]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I've got an error log from one of customers.

```
TypeError: Cannot read property 'sendWithPromise' of null
  at e.getPage(/main.fcbd366b59adeaccde73.js:1:2580545)
  at e.getPage(/main.fcbd366b59adeaccde73.js:1:2562311)
  at e.renderPage(/main.fcbd366b59adeaccde73.js:1:2100087)
  at e.updateSize(/main.fcbd366b59adeaccde73.js:1:2098625)
  at ? (/main.fcbd366b59adeaccde73.js:1:2095964)
  at i(/main.fcbd366b59adeaccde73.js:1:2155073)
  at t.invokeTask(/polyfills.6daafc40a5cb42269e22.js:1:8745)
  at Object.onInvokeTask(/main.fcbd366b59adeaccde73.js:1:313689)
  at t.invokeTask(/polyfills.6daafc40a5cb42269e22.js:1:8666)
  at e.runTask(/polyfills.6daafc40a5cb42269e22.js:1:3929)
  at e.invokeTask(/polyfills.6daafc40a5cb42269e22.js:1:9835)
  at invoke(/polyfills.6daafc40a5cb42269e22.js:1:9726)
  at n.args.(anonymous function)(/polyfills.6daafc40a5cb42269e22.js:1:25027)
```

I couldn't reproduce the issue but here are my thoughts.

It seems that this error appears after a user tries to change page index in the PDF preview.
The piece of code where the issue happenes looks like this 

```
var l=this.messageHandler.sendWithPromise("GetPage",{pageIndex:t}).then(function(e){if(n.destroyed)throw new Error("Transport destroyed");var l=new M(t,e,n,n._params.pdfBug);
```

Since the issue happens after `renderPage` and `getPage` my guess is that the source of issue is the not initialized `_pdf` variable which is at 388 line of this file 
https://github.com/VadimDez/ng2-pdf-viewer/blob/master/src/app/pdf-viewer/pdf-viewer.component.ts

Could it be that I'm right and that additional check like this 
```
if (!this._pdf) {
      return;
    }
```
could fix the issue? 
Thanks

**Comment by sanderj6** [comment]
Did you ever solve this issue?

**Comment by Avenel** [comment]
I am curious, too. I do encounter that error in our application sometimes. Unfortunately it is not consistently to reproduce at all.

**Comment by MLDMoritz** [comment]
I have the same behavior, but on a Vue project! So it has to do something with pdf-js

https://github.com/FranckFreiburger/vue-pdf/
