### ISSUE TITLE
can't compile v5.3.2 

### ISSUE THREAD

**Issue by Avareto** [VadimDez/ng2-pdf-viewer#490]
[11:06:57]  typescript: @types/pdfjs-dist/index.d.ts, line: 7
            Invalid 'reference' directive syntax.

       L6:      then<U>(onResolve: (promise: T) => U, onReject?: (reason: string) => void): PDFPromise<U>;

[11:06:57]  typescript: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts, line: 39
            Type 'CustomEvent' is not generic.

      L38:  onError: EventEmitter<any>;
      L39:  onProgress: EventEmitter<PDFProgressData>;
      L40:  pageChange: EventEmitter<number>;

[11:06:57]  typescript: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts, line: 40
            Type 'CustomEvent' is not generic.

      L39:  onProgress: EventEmitter<PDFProgressData>;
      L40:  pageChange: EventEmitter<number>;
      L41:  src: string | Uint8Array | PDFSource;

**Comment by VadimDez** [comment]
I've just tried with a fresh `ng` project to do `ng serve` as well as `ng build --prod` - had no problems.
Could you explain how to reproduce this? Thank you.

**Comment by Avareto** [comment]
Sorry, I forgot to mention that I still use Angular 7.x

**Comment by VadimDez** [comment]
it looks more like a `typescript` error, maybe you're using an old version?

**Comment by SyedAkmal** [comment]
what's the solution in angular6?
with the following versions.

Angular CLI: 6.2.9
Node: 8.9.4
OS: darwin x64
Angular: 6.1.8

Please provide a solution to this!

**Comment by VadimDez** [comment]
@SyedAkmal  what error do you get?

**Comment by AndrWeisR** [comment]
I get the same errors exactly in an Ionic 3 project (built with Angular 5.2.9).

```
> ionic-app-scripts build --target cordova --platform android
[16:44:04]  ionic-app-scripts 3.1.9 
[16:44:04]  build dev started ...
[16:44:04]  clean started ...
[16:44:04]  clean finished in 25 ms
[16:44:04]  copy started ...
[16:44:05]  deeplinks started ...
[16:44:05]  deeplinks finished in 186 ms
[16:44:05]  transpile started ...
Building for PROD
[16:44:08]  typescript: c:/MobileDev/MyClaimScanBot/node_modules/@types/pdfjs-dist/index.d.ts, line: 7 
            Invalid 'reference' directive syntax.

       L6:      then<U>(onResolve: (promise: T) => U, onReject?: (reason: string) => void): PDFPromise<U>;

[16:44:08]  typescript: ...ScanBot/node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts, line: 39 
            Type 'CustomEvent' is not generic.

      L38:  onError: EventEmitter<any>;
      L39:  onProgress: EventEmitter<PDFProgressData>; 
      L40:  pageChange: EventEmitter<number>;

[16:44:08]  typescript: ...ScanBot/node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts, line: 40 
            Type 'CustomEvent' is not generic.

      L39:  onProgress: EventEmitter<PDFProgressData>;
      L40:  pageChange: EventEmitter<number>;               
      L41:  src: string | Uint8Array | PDFSource;

[16:44:08]  ionic-app-script task: "build" 
[16:44:08]  Error: Failed to transpile program 
Error: Failed to transpile program
    at new BuildError (c:\MobileDev\MyClaimScanBot\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at c:\MobileDev\MyClaimScanBot\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (c:\MobileDev\MyClaimScanBot\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (c:\MobileDev\MyClaimScanBot\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at c:\MobileDev\MyClaimScanBot\node_modules\@ionic\app-scripts\dist\build.js:109:82
[ERROR] An error occurred while running subprocess ionic-app-scripts.
```

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Android)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 8.1
```

**Comment by maxhsantos** [comment]
the same error here

**Comment by gmarab** [comment]
the same error here

**Comment by VadimDez** [comment]
Have you tried updating typescript version?

**Comment by gmarab** [comment]
I use typecript version 2.6.2.
The most recent version you can use with Angular 5.

**Comment by StongSir** [comment]
the same error here,
  I'm work With   
`
Ionic 3.9.0   
 Angular 5.0.0
 Typescript  2.4.2
`

**Comment by ljudbane** [comment]
I

> the same error here,
> I'm work With
> `Ionic 3.9.0 Angular 5.0.0 Typescript 2.4.2`

I'm also using the same version of Ionic and got the same error when i upgraded the lib. I went back to version 5.1.1 and that one works. Not really a solution, but maybe it will help somebody.

**Comment by Story5** [comment]
got the same error
```
Ionic:

   Ionic CLI          : 5.2.8 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 26 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```
