### ISSUE TITLE
pdfjsLib is undefined

### ISSUE THREAD

**Issue by Vi-dot** [VadimDez/ng2-pdf-viewer#55]
Hello,

I'm trying to use the  #master version in my project, and I got this error when website is loaded :
```pdfjsLib is undefined```

I'm not sure but it looks like it comes from the angular-cli I updated in my project.

Someone already got this problem ?

**Comment by Vi-dot** [comment]
It's strange because I have not this problem with 1.0.2 release. What is the right way to produce dist directory ?

**Comment by VadimDez** [comment]
Are you just cloning master branch, did i understand right ?

**Comment by Vi-dot** [comment]
Yes just master branch, you understand right

**Comment by VadimDez** [comment]
i made mistake and started to developed 2.0.0 in master... so it's not yet ready there

**Comment by Vi-dot** [comment]
Ok, but the thing is I have also this error with my previous stable fork (#pdfviewer-way-pr).
I don't understand where it comes from, as I don't know fine how works configurations in angular-cli.
Have you also this error with master ?
What the difference between master and 1.0.2 about library linking ? (because 1.0.2 don't gives this error)

**Comment by shabbir-dhangot** [comment]
I am facing same issue.
This is entry in my package.json folder
"ng2-pdf-viewer": "1.0.2",

How to solve this?

**Comment by Vi-dot** [comment]
I get also this error during testing library with the demo app, `npm run all` gives a better trace :
```
Error: (SystemJS) pdfjsLib is undefined
	@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:125:5
	__w_pdfjs_require__@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:45:12
	@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:2659:15
	__w_pdfjs_require__@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:45:12
	@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:3367:25
	__w_pdfjs_require__@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:45:12
	@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:91:18
	@http://localhost:8000/lib/pdfjs-dist/web/pdf_viewer.js:26:18
	@http://localhost:8000/pdf-viewer/pdf-viewer.component.js:18:1
	@http://localhost:8000/pdf-viewer/pdf-viewer.component.js:1:31
	@http://localhost:8000/pdf-viewer/pdf-viewer.component.js:1:2
	@http://localhost:8000/app/app.component.js:12:30
	@http://localhost:8000/app/app.component.js:1:31
	@http://localhost:8000/app/app.component.js:1:2
	@http://localhost:8000/app.module.js:14:23
	@http://localhost:8000/app.module.js:1:31
	@http://localhost:8000/app.module.js:1:2
	@http://localhost:8000/main.js:3:20
	@http://localhost:8000/main.js:1:31
	@http://localhost:8000/main.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:8000/lib/zone.js/dist/zone.js:232:17
	Zone.prototype.run@http://localhost:8000/lib/zone.js/dist/zone.js:114:24
	scheduleResolveOrReject/<@http://localhost:8000/lib/zone.js/dist/zone.js:502:52
	ZoneDelegate.prototype.invokeTask@http://localhost:8000/lib/zone.js/dist/zone.js:265:21
	Zone.prototype.runTask@http://localhost:8000/lib/zone.js/dist/zone.js:154:28
	drainMicroTaskQueue@http://localhost:8000/lib/zone.js/dist/zone.js:401:25
	ZoneTask/this.invoke@http://localhost:8000/lib/zone.js/dist/zone.js:339:25
	
	Evaluating http://localhost:8000/pdf-viewer/pdf-viewer.component.js
	Evaluating http://localhost:8000/app/app.component.js
	Evaluating http://localhost:8000/app.module.js
	Evaluating http://localhost:8000/main.js
	Error loading http://localhost:8000/main.js
```

**Comment by Vi-dot** [comment]
There is an other trace after `gulp build`
```
[12:01:46] 'compile' errored after 5.24 s
[12:01:46] Error: Command failed: ./node_modules/.bin/ngc -p tsconfig-aot.json
Error at /it/_ng2-pdf-viewer/node_modules/@types/jasmine/index.d.ts:39:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at /it/_ng2-pdf-viewer/node_modules/@types/jasmine/index.d.ts:39:46: Cannot find name 'keyof'.
Error at /it/_ng2-pdf-viewer/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng2-pdf-viewer@0.1.5 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-pdf-viewer@0.1.5 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-pdf-viewer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-pdf-viewer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-pdf-viewer
npm ERR! There is likely additional logging output above.
```

**Comment by Vi-dot** [comment]
@VadimDez 
I almost sure that this bug appears only with lastest node/npm.
As @shabbir-dhangot I cannot even build 1.0.2 from branch features/1.0.2.
Which version of node/npm do you used to build 1.0.2 release ?

**Comment by VadimDez** [comment]
@Vi-dot I'm using v6.9.5

**Comment by Vi-dot** [comment]
@VadimDez  still not works :/ Strange
I clear and tried to build features/1.0.2 with those versions :
```
node v6.9.5
npm  v3.10.10
```

**Comment by Vi-dot** [comment]
I fixed it by adding at begging this include :
```"../node_modules/pdfjs-dist/build/pdf.js"```

Then if you have an angular-cli project, add this path in angular-cli.json in "scripts" field.

I don't know if it exists a best solution to include it in ng2-pdf-viewer instead of project.
