### ISSUE TITLE
Uncaught (in promise): UnexpectedResponseException: Unexpected server response (0) while retrieving PDF "https://vadimdez.github.io/ng2-pdf-viewer/pdf-test.pdf". 

### ISSUE THREAD

**Issue by jepiqueau** [VadimDez/ng2-pdf-viewer#60]
i am using ng2-pdf-viewer in Ionic2

when i use  pdfSrc: string = 'https://vadimdez.github.io/ng2-pdf-viewer/pdf-test.pdf'; in my Home Page component it works
but when i use
 pdfSrc: any = {
    url: 'https://vadimdez.github.io/ng2-pdf-viewer/pdf-test.pdf',
    withCredentials: true,
    httpHeaders: { // cross domain
      'Access-Control-Allow-Credentials': true
    }
  };
i got the following error
Error: Uncaught (in promise): UnexpectedResponseException: Unexpected server response (0) while retrieving PDF "https://vadimdez.github.io/ng2-pdf-viewer/pdf-test.pdf".
Error
    at UnexpectedResponseExceptionClosure (http://localhost:8100/build/main.js:108329:42)
    at Object.<anonymous> (http://localhost:8100/build/main.js:108332:2)
    at Object.<anonymous> (http://localhost:8100/build/main.js:110178:30)
    at __w_pdfjs_require__ (http://localhost:8100/build/main.js:107897:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:165178:23)
    at __w_pdfjs_require__ (http://localhost:8100/build/main.js:107897:30)
    at globalScope (http://localhost:8100/build/main.js:107943:18)
    at http://localhost:8100/build/main.js:107946:10
    at webpackUniversalModuleDefinition (http://localhost:8100/build/main.js:107870:20)
    at Object.<anonymous> (http://localhost:8100/build/main.js:107877:3)
    at s (http://localhost:8100/build/polyfills.js:3:4211)
    at s (http://localhost:8100/build/polyfills.js:3:4034)
    at http://localhost:8100/build/polyfills.js:3:4574
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:35138:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7083)
    at i (http://localhost:8100/build/polyfills.js:3:3671)
    at XMLHttpRequest.invoke (http://localhost:8100/build/polyfills.js:3:10876)

my platform data

Ionic Framework: 2.1.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.1.3
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.3.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

Can you please help me. Now i would like to view pdf files residing on an external server, how the server should be set-up to allow CORS

**Comment by filippodicostanzo** [comment]
I have the same error

**Comment by VadimDez** [comment]
Seems like github does not support `OPTIONS` request.

**Comment by jorawarsingh** [comment]
getting this any idea? this was working fine. current version 1.2.0

> src  blob:http://localhost:8080/a81563a2-4a32-46af-8b69-0db0bf947263
> error {"name":"UnexpectedResponseException","message":"Unexpected server response (200) while retrieving PDF \"blob:http://localhost:8080/a81563a2-4a32-46af-8b69-0db0bf947263\".","status":200,"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}
