### ISSUE TITLE
build prod fails using version 6.2.0 and 6.1.2

### ISSUE THREAD

**Issue by Farahatology** [VadimDez/ng2-pdf-viewer#603]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\WebUI\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:245:35)
    at checkNodeForDecorators (D:\WebUI\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:70:21)
    at visitNodes (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15788:30)
    at Object.forEachChild (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:16014:24)
    at checkNodeForDecorators (D:\WebUI\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:61:31)
    at visitNode (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15779:24)
    at Object.forEachChild (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15909:21)
    at checkNodeForDecorators (D:\WebUI\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:61:31)
    at visitNode (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15779:24)
    at Object.forEachChild (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15966:24)
    at checkNodeForDecorators (D:\WebUI\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:61:31)
    at visitNode (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15779:24)
    at Object.forEachChild (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15977:24)
    at checkNodeForDecorators (D:\WebUI\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:61:31)
    at visitNode (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15779:24)
    at Object.forEachChild (D:\WebUI\ClientApp\node_modules\typescript\lib\typescript.js:15873:21)

**Comment by Farahatology** [comment]
Current Environment 
`Angular CLI: 7.1.0
Node: 12.16.2
OS: win32 x64
Angular: 7.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.0
@angular-devkit/build-angular     0.11.0
@angular-devkit/build-optimizer   0.11.0
@angular-devkit/build-webpack     0.11.0
@angular-devkit/core              7.1.0
@angular-devkit/schematics        7.1.0
@angular/cdk                      7.3.7
@angular/cli                      7.1.0
@ngtools/webpack                  7.1.0
@schematics/angular               7.1.0
@schematics/update                0.11.0
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
`

**Comment by p0w4p0ty** [comment]
Hi,

A possible fix for this:

> For a library to work well with versions 6 and 7 of @angular/cli, you must export all decorators metadata when building the library. To do that, add the following to the tsconfig.json of your lib:
> "compilerOptions": {
>   "emitDecoratorMetadata": true
> }

Source: https://stackoverflow.com/a/60887133

**Comment by NikhilP97** [comment]
After searching for a long time, this worked for me. Upgraded @angular-devkit/build-angular to version: "~0.803.19" and then prod build worked fine. Made the following change in package.json.
`
"devDependencies": {

    "@angular-devkit/build-angular": "~0.803.19",
   ...
}
`

**Comment by EricLewe** [comment]
Another cause of this issue was due to wrong cli version:
https://github.com/VadimDez/ng2-pdf-viewer/issues/594#issuecomment-927271784
