### ISSUE TITLE
ngg missing dependencies pdfjs-dist

### ISSUE THREAD

**Issue by MRisto** [VadimDez/ng2-pdf-viewer#839]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Hey, i searched for this issue but i could not find anything.

I have this error during compiling in the ci. And i have no clue what the issue is.

``` 
Compiling @angular/material/progress-spinner : es2015 as esm2015
An error occurred during the build:
Error: The target entry-point "ng2-pdf-viewer" has missing dependencies:
 - pdfjs-dist/legacy/build/pdf
 - pdfjs-dist/legacy/web/pdf_viewer
    at TargetedEntryPointFinder.findEntryPoints (/builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40:23)
    at /builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:28:29)
    at /builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (/builds/dytab/dytab/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (/builds/dytab/dytab/node_modules/@ngtools/webpack/src/ngcc_processor.js:175:16)
    at /builds/dytab/dytab/node_modules/@ngtools/webpack/src/ivy/host.js:146:18
    at /builds/dytab/dytab/node_modules/@ngtools/webpack/src/ivy/host.js:76:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (/builds/dytab/dytab/node_modules/@ngtools/webpack/src/ivy/host.js:74:32)
    at /builds/dytab/dytab/node_modules/@ngtools/webpack/src/ivy/host.js:75:55
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (/builds/dytab/dytab/node_modules/@ngtools/webpack/src/ivy/host.js:74:32)
The target entry-point "ng2-pdf-viewer" has missing dependencies:
 - pdfjs-dist/legacy/build/pdf
 - pdfjs-dist/legacy/web/pdf_viewer
```

I have the following packages:
```
   "@angular/cdk": "12.2.7",
    "@angular/common": "12.2.7",
    "@angular/compiler": "12.2.7",
    "@angular/core": "12.2.7",
    "@angular/forms": "12.2.7",
    "@angular/material": "12.2.7",
    "@angular/platform-browser": "12.2.7",
    "@angular/platform-browser-dynamic": "12.2.7",
    "ng2-pdf-viewer": "^7.0.2",
```

Things i tried:
1. Updated to newest version of ng2-pdf-viewer
2. Install pdfjs-dist itself as a package

Has anyone a tip, how i could fix it?

**Comment by MRisto** [comment]
Oh i saw that it works with installing the pdfjs-dist as dependency. Is this bad? Or can i add the dependency there?
