### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'selectors')

### ISSUE THREAD

**Issue by sonntag-philipp** [VadimDez/ng2-pdf-viewer#854]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

# Error Message
```
main.2e189a4924fd46f1.js:1 Unhandled generic error TypeError: Cannot read properties of null (reading 'selectors')
    at main.2e189a4924fd46f1.js:1:55851
    at M_ (main.2e189a4924fd46f1.js:1:55947)
    at main.2e189a4924fd46f1.js:1:69154
    at ie (main.2e189a4924fd46f1.js:1:69298)
    at template (main.2e189a4924fd46f1.js:1:518493)
    at kC (main.2e189a4924fd46f1.js:1:53120)
    at fg (main.2e189a4924fd46f1.js:1:51282)
    at UP (main.2e189a4924fd46f1.js:1:59363)
    at main.2e189a4924fd46f1.js:1:51483
    at fg (main.2e189a4924fd46f1.js:1:51494)
```

# Reproduction
1. Install the dependencies
2. Run a production build
3. Try to open a new document
4. Described Error should appear

# Additional information
- The bug only occurs in the *first* build after I installed the dependencies
  - Rebuilding without installing the dependencies fixes this issue temporarily
- The bug doesn't occur when using *npm* instead of *pnpm*

# Angular Version
```
Angular CLI: 13.1.4
Node: 14.15.0
Package Manager: pnpm 6.26.1
OS: darwin x64

Angular: 13.1.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@ngtools/webpack                13.1.4
@schematics/angular             13.1.4
ng-packagr                      13.1.3
rxjs                            6.6.7
typescript                      4.5.4
webpack                         5.66.0
```

# Installed Dependencies
```
    "dependencies": {
        "@angular/animations": "~13.1.1",
        "@angular/cdk": "~13.1.1",
        "@angular/common": "~13.1.1",
        "@angular/compiler": "~13.1.1",
        "@angular/core": "~13.1.1",
        "@angular/forms": "~13.1.1",
        "@angular/material": "~13.1.1",
        "@angular/platform-browser": "~13.1.1",
        "@angular/platform-browser-dynamic": "~13.1.1",
        "@angular/router": "~13.1.1",
        "@angular/service-worker": "~13.1.1",
        "@capacitor/core": "2.3.0",
        "@ionic/angular": "^6.0.2",
        "@ngx-translate/core": "^14.0.0",
        "@ngx-translate/http-loader": "^7.0.0",
        "bindings": "^1.5.0",
        "file-saver-es": "^2.0.5",
        "jsrsasign-reduced": "^8.0.15",
        "jwt-decode": "^2.2.0",
        "ng2-pdf-viewer": "^7.0.2",
        "ngx-toastr": "^14.2.1",
        "pdfjs-dist": "2.11.338",
        "rxjs": "~6.6.3",
        "scandit-sdk": "^5.8.0",
        "three": "^0.136.0",
        "tslib": "^2.3.1",
        "zone.js": "~0.11.4"
    },
    "devDependencies": {
        "@angular-devkit/architect": "~0.1301.2",
        "@angular-devkit/build-angular": "~13.1.2",
        "@angular-devkit/core": "~13.1.2",
        "@angular-devkit/schematics": "~13.1.2",
        "@angular/cli": "~13.1.2",
        "@angular/compiler-cli": "~13.1.1",
        "@angular/language-service": "~13.1.1",
        "@capacitor/cli": "~2.4.6",
        "@ionic/cli": "^6.17.1",
        "@ngtools/webpack": "^13.1.2",
        "@types/jasmine": "~3.6.0",
        "@types/jasminewd2": "~2.0.8",
        "@types/node": "^12.19.16",
        "@types/pdfjs-dist": "~2.0.1",
        "@typescript-eslint/eslint-plugin": "^4.13.0",
        "@typescript-eslint/parser": "^4.13.0",
        "core-js": "^3.20.2",
        "eslint": "^7.17.0",
        "eslint-config-prettier": "^7.1.0",
        "eslint-plugin-prettier": "^3.3.1",
        "eslint-plugin-rxjs": "^2.1.6",
        "http-server": "^14.0.0",
        "jasmine-core": "~3.6.0",
        "jasmine-spec-reporter": "~5.0.0",
        "karma": "~6.3.9",
        "karma-chrome-launcher": "~3.1.0",
        "karma-jasmine": "~4.0.0",
        "karma-summary-reporter": "^2.0.2",
        "ng-packagr": "^13.1.2",
        "prettier": "2.2.1",
        "puppeteer": "^13.0.1",
        "replace-in-file": "^6.3.2",
        "ts-node": "10.2.1",
        "typescript": "~4.5.4",
        "webpack": "^5.65.0"
    }
```

**Comment by sonntag-philipp** [comment]
# Related issues
- https://github.com/pnpm/pnpm/issues/3410
- https://github.com/angular/angular-cli/issues/21622
- https://github.com/angular/angular-cli/issues/16980

It seems that Angular has some incompatibilities.

**Comment by VadimDez** [comment]
Could you please test if latest version 8.0.0 fixes your issue?
