### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'query') when dispatching 'find' event

### ISSUE THREAD

**Issue by marja-w** [VadimDez/ng2-pdf-viewer#931]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I am trying to highlight words in my PDF by using the suggested approach in from the documenation:

`this.pdfComponent?.pdfViewer.eventBus.dispatch('find', {
      query: stringToSearch, type: 'again', caseSensitive: false, findPrevious: undefined, highlightAll: true, phraseSearch: true
    });`

When I run the code, I get an error:

`Uncaught (in promise): TypeError: Cannot read properties of null (reading 'query')
TypeError: Cannot read properties of null (reading 'query')
    at get _query [as _query] (http://localhost:4200/libs_data-sheet-extractor_feature-shell_src_index_ts.js:23474:29)
    at PDFFindController._calculateMatch (http://localhost:4200/libs_data-sheet-extractor_feature-shell_src_index_ts.js:23604:30)
    at http://localhost:4200/libs_data-sheet-extractor_feature-shell_src_index_ts.js:23743:24
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:8158:160)
    at Object.onInvoke (http://localhost:4200/vendor.js:101363:25)
    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:8158:48)
    at Zone.run (http://localhost:4200/polyfills.js:7884:37)
    at http://localhost:4200/polyfills.js:9304:28
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:8191:173)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:101351:25)`

My variable `stringToSearch` is a string and I specifically checked, if it is null, which is not the case. I am using Angular Version 14.8.3 and ng2-pdf-viewer version 9.0.0.

Any help is appreciated.

**Comment by marja-w** [comment]
[Here](https://github.com/VadimDez/ng2-pdf-viewer/issues/925) I found out that you are supposed to use the code `this.pdfComponent.pdfFindController.executeCommand(...)`. This should be updated in the documentation.
