### ISSUE TITLE
Enabled Stick To Page throws Error if new pdf is loaded

### ISSUE THREAD

**Issue by AnWeber** [VadimDez/ng2-pdf-viewer#946]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

Enabled Stick To Page throws `Cannot read properties of undefined (reading 'div')` 

## Steps to reproduce
- Open https://vadimdez.github.io/ng2-pdf-viewer/
- enable stick to page
- load pdf
- Error in DevTools

```
main.3e9af18ed70fa737.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'div')
    at B.Yt (main.3e9af18ed70fa737.js:1:968265)
    at B.Ve (main.3e9af18ed70fa737.js:1:968861)
    at B.value (main.3e9af18ed70fa737.js:1:943447)
    at B.set (main.3e9af18ed70fa737.js:1:943166)
    at main.3e9af18ed70fa737.js:1:582209
    at g.<computed> (polyfills.e4a1de4afc8f1d46.js:1:33192)
    at _.value (polyfills.e4a1de4afc8f1d46.js:1:8140)
    at Object.onInvokeTask (main.3e9af18ed70fa737.js:1:119127)
    at _.value (polyfills.e4a1de4afc8f1d46.js:1:8061)
    at p.value (polyfills.e4a1de4afc8f1d46.js:1:2339)
```
![stick_to_page](https://user-images.githubusercontent.com/13434739/203071534-8cefb17d-9aae-4eac-8f81-fc99f6dcf45a.gif)

**Comment by AnWeber** [comment]
remove stale

**Comment by AnWeber** [comment]
not stale
