### ISSUE TITLE
build failure for --prod

### ISSUE THREAD

**Issue by praveenpds** [VadimDez/ng2-pdf-viewer#96]
Error is : 

D:\web\Code\Mobile\IonicApp>ionic run android --prod

> IonicApp@1.0.0 ionic:build D:\web\Code\Mobile\IonicApp
> ionic-app-scripts build "--prod"

[10:42:29]  ionic-app-scripts 1.3.7
[10:42:29]  build prod started ...
[10:42:29]  clean started ...
[10:42:29]  clean finished in less than 1 ms
[10:42:29]  copy started ...
[10:42:29]  ngc started ...
[10:42:39]  ngc finished in 9.83 s
[10:42:39]  preprocess started ...
[10:42:39]  deeplinks started ...
[10:42:40]  deeplinks finished in 530 ms
[10:42:40]  optimization started ...
[10:42:41]  copy finished in 11.19 s
[10:42:51]  optimization finished in 11.64 s
[10:42:51]  preprocess finished in 12.17 s
[10:42:51]  webpack started ...
[10:43:03]  ionic-app-script task: "build"
[10:43:03]  Error: ./~/pdfjs-dist/build/pdf.combined.js Module build failed: RangeError: Maximum call stack size
            exceeded at getResolvedSymbol
            (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33244:35) at
            isMatchingReference
            (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33300:67) at
            getTypeAtFlowArrayMutation
            (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33913:21) at
            getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
            at getTypeAtFlowArrayMutation
            (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33914:36) at
            getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
            at getTypeAtFlowArrayMutation
            (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33914:36) at
            getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
            at getTypeAtFlowArrayMutation
            (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33914:36) at
            getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
            @ ./~/ng2-pdf-viewer/dist/pdf-viewer.component.js 4:0-40 @
            ./src/pages/pdf-viewer/ng-pdf-viewer.component.ngfactory.ts @ ./src/app/app.module.ngfactory.ts @
            ./src/app/main.ts
Error: ./~/pdfjs-dist/build/pdf.combined.js
Module build failed: RangeError: Maximum call stack size exceeded
    at getResolvedSymbol (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33244:35)
    at isMatchingReference (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33300:67)
    at getTypeAtFlowArrayMutation (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33913:21)
    at getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
    at getTypeAtFlowArrayMutation (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33914:36)
    at getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
    at getTypeAtFlowArrayMutation (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33914:36)
    at getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
    at getTypeAtFlowArrayMutation (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33914:36)
    at getTypeAtFlowNode (D:\web\Code\Mobile\IonicApp\node_modules\typescript\lib\typescript.js:33847:32)
 @ ./~/ng2-pdf-viewer/dist/pdf-viewer.component.js 4:0-40
 @ ./src/pages/pdf-viewer/ng-pdf-viewer.component.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (D:\web\Code\Mobile\IonicApp\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (D:\web\Code\Mobile\IonicApp\node_modules\@ionic\app-scripts\dist\webpack.js:119:28)
    at D:\web\Code\Mobile\IonicAppechanic\node_modules\webpack\lib\Compiler.js:256:15
    at Compiler.emitRecords (D:\web\Code\Mobile\IonicApp\node_modules\webpack\lib\Compiler.js:351:37)
    at D:\web\Code\Mobile\IonicAppechanic\node_modules\webpack\lib\Compiler.js:249:12
    at D:\web\Code\Mobile\IonicApp\node_modules\webpack\lib\Compiler.js:344:11
    at next (D:\web\Code\Mobile\IonicApp\node_modules\tapable\lib\Tapable.js:154:11)
    at Compiler.<anonymous> (D:\web\Code\Mobile\IonicApp\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\web\Code\Mobile\IonicApp\node_modules\tapable\lib\Tapable.js:158:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! IonicApp@1.0.0 ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the IonicApp@1.0.0 ionic:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxx\AppData\Roaming\npm-cache\_logs\2017-06-14T05_13_03_386Z-debug.log

**Comment by mhartington** [comment]
This should be closed, as it is not an issue with this library.

**Comment by VadimDez** [comment]
@praveenpds do you still have the issue with the latest version `3.0.2`?

**Comment by praveenpds** [comment]
Fixed :)

**Comment by shaikh486** [comment]
build prod failed: Cannot determine the module for class PdfViewerComponent in
            D:/ambuja_work/apps/Foundations/node_modules/ng2-pdf-viewer/dist/pdf-viewer.component.d.ts!
Error: Cannot determine the module for class PdfViewerComponent in D:/ambuja_work/apps/Foundations/node_modules/ng2-pdf-viewer/dist/pdf-viewer.component.d.ts!
    at analyzeAndValidateNgModules (D:\ambuja_work\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:12707:17)
    at OfflineCompiler.compileModules (D:\ambuja_work\apps\Foundations\node_modules\@angular\compiler\bundles\compiler.umd.js:12775:20)
    at CodeGenerator.codegen (D:\ambuja_work\apps\Foundations\node_modules\@angular\compiler-cli\src\codegen.js:58:30)
    at Object.runCodegen (D:\ambuja_work\apps\Foundations\node_modules\@ionic\app-scripts\dist\aot\codegen\codegen-ng22.js:15:26)
    at Object.doCodegen (D:\ambuja_work\apps\Foundations\node_modules\@ionic\app-scripts\dist\aot\codegen.js:6:31)
    at D:\ambuja_work\apps\Foundations\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:41:30
[20:26:53]  copy finished in 7.25 s

**Comment by harshadduasane** [comment]
Hi,
I'm facing the following issue when firing --prod command
 typescript error
 <pdf-viewer [ERROR ->][src]="pdfSrc" [render-text]="true" [original-size]="false"></pdf-viewer>
